pipeline {
    agent any

    stages {
        stage('Check for changes in NewAADUsers.csv') {
            steps {
                script {
                    // Fetch commit logs for NewAADUsers.csv
                    def commitLogs = sh(script: 'curl -s https://api.github.com/repos/solunistresearch/Azure_AD_UserAddition/commits?path=NewAADUsers.csv', returnStdout: true).trim()
                    echo "Commit logs: ${commitLogs}"
                }
            }
        }
        
        stage('Adding user in the Azure AD') {
            steps {
                script {
                    // Download the PowerShell script
                    sh 'curl -s -O https://github.com/solunistresearch/Azure_AD_UserAddition/raw/main/Add-NewAADUsers.ps1'
                    
                    // Execute the PowerShell script
                    def scriptOutput = powershell(returnStdout: true, script: '.\\Add-NewAADUsers.ps1')
                    echo "Script output: ${scriptOutput}"
                }
            }
        }
        
        stage('Output check') {
            steps {
                script {
                    // Print the output of the script executed in the previous stage
                    echo "Script output: ${scriptOutput}"
                }
            }
        }
    }

    triggers {
        pollSCM('*/5 * * * *') // Schedule the pipeline to check for changes every 5 minutes
    }
}
